name: Go

on:
  push:
    branches: [ '*' ]
    tags: [ '*.*.*', '*.*.*-*', 'test-release-*' ]
  pull_request:
    branches: [ 'main', 'v*.*.*', 'remote-registry' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    outputs:
      sha_short: ${{steps.vars.outputs.sha_short}}
      arch: ${{steps.vars.outputs.arch}}
      os: ${{steps.vars.outputs.os}}
    strategy:
      matrix:
        arch: [amd64,arm64]
        cgo: [0]
        os: [windows-latest, ubuntu-latest ]
        include:
          - os: macos-latest
            arch: arm64
            cgo: 1
          - os: macos-latest
            arch: amd64
            cgo: 1

    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26.3

    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: gh-pages/package-lock.json

    - name: generate vars
      id: vars
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "arch=${{matrix.arch}}" >> $GITHUB_OUTPUT
        echo "os=$(go run test/get-os.go)" >> $GITHUB_OUTPUT
        echo "ext=$(go run test/get-os.go extension)" >> $GITHUB_OUTPUT

    - name: Build
      env:
        GOARCH: ${{matrix.arch}}
        CGO_ENABLED: ${{matrix.cgo}}
      shell: bash
      run: |
        ./build.sh -v ${{github.ref_name}} -b ${{github.run_number}} -n cola -l "Command Launcher" -o build/cola_${{steps.vars.outputs.os}}_${{matrix.arch}}_${{steps.vars.outputs.sha_short}}

    - name: Test & Benchmark
      run: go test -v ./...

    - name: Integration-test
      run: |
        echo "${{github.workspace}}/test"
        SCRIPT_DIR='${{github.workspace}}/test' test/integration.sh
      shell: bash

    - name: documentation lint
      run: cd gh-pages && npm install && npm run test

    - name: Upload binary
      uses: actions/upload-artifact@v7
      with:
        name: ${{steps.vars.outputs.os}}-cola-${{matrix.arch}}
        path: build/cola_${{steps.vars.outputs.os}}_${{matrix.arch}}_${{steps.vars.outputs.sha_short}}

    - name: Rename binary name for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mv build/cola_${{steps.vars.outputs.os}}_${{matrix.arch}}_${{steps.vars.outputs.sha_short}} build/cola_${{steps.vars.outputs.os}}_${{matrix.arch}}_${{github.ref_name}}${{steps.vars.outputs.ext}}

    - name: Release
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/cola_${{steps.vars.outputs.os}}_${{matrix.arch}}_${{github.ref_name}}${{steps.vars.outputs.ext}}

  packaging:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download linux amd64 artifact
        uses: actions/download-artifact@v8
        with:
          name: linux-cola-amd64
          path: output/linux/amd64/
      - name: Download linux arm64 artifact
        uses: actions/download-artifact@v8
        with:
          name: linux-cola-arm64
          path: output/linux/arm64/
      - name: Download windows amd64 artifact
        uses: actions/download-artifact@v8
        with:
          name: windows-cola-amd64
          path: output/windows/amd64/
      - name: Download darwin amd64 artifact
        uses: actions/download-artifact@v8
        with:
          name: darwin-cola-amd64
          path: output/darwin/amd64/
      - name: Download darwin-arm64 artifact
        uses: actions/download-artifact@v8
        with:
          name: darwin-cola-arm64
          path: output/darwin/arm64/

      - name: Rename binary name
        run: |
          mv output/darwin/arm64/cola_darwin_arm64_${{needs.build.outputs.sha_short}} output/darwin/arm64/cola
          mv output/darwin/amd64/cola_darwin_amd64_${{needs.build.outputs.sha_short}} output/darwin/amd64/cola
          mv output/linux/amd64/cola_linux_amd64_${{needs.build.outputs.sha_short}} output/linux/amd64/cola
          mv output/linux/arm64/cola_linux_arm64_${{needs.build.outputs.sha_short}} output/linux/arm64/cola
          mv output/windows/amd64/cola_windows_amd64_${{needs.build.outputs.sha_short}} output/windows/amd64/cola.exe

      - name: Zip the package
        uses: thedoctor0/zip-release@0.7.6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          type: 'zip'
          filename: cola_${{github.ref_name}}.zip
          directory: output

      - name: Upload
        uses: actions/upload-artifact@v7
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: all-in-one.zip
          path: output/cola_${{github.ref_name}}.zip

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: output

      - name: Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/cola_${{github.ref_name}}.zip


  update-latest-version:
    needs: [ packaging ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Generate latest version file
        run: |
          mkdir output
          cat release-notes.yaml | yq -r '."${{github.ref_name}}"' > output/latest.yaml

      - name: Display latest version file content
        run: cat output/latest.yaml

      - name: Upload latest version index
        uses: actions/upload-artifact@v7
        with:
          name: latest.yaml
          path: output/latest.yaml

      - name: Release & Update the version index
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/latest.yaml



